# Generated by Django 4.2.4 on 2023-08-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_420', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='flower_flavor3',
            new_name='flower_aroma',
        ),
        migrations.AddField(
            model_name='form',
            name='grow_info',
            field=models.CharField(default='not applicable', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='user_notes',
            field=models.CharField(max_length=500),
        ),
    ]
